<?php

use App\Model\EpisodePresentateur;
use Illuminate\Database\Seeder;

class EpisodePresentateurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        EpisodePresentateur::insert([
            // Saison 2 (5 épisodes)
            ['episode_id' => '1',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '2',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '3',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '4',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '5',
                'presentateur_id' => '1',
            ],

            // Saison 3 (8 épisodes)
            ['episode_id' => '6',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '7',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '8',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '9',
            'presentateur_id' => '1',
            ],
            ['episode_id' => '10',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '11',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '12',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '13',
                'presentateur_id' => '1',
            ],

            // Saison 4 (13 épisodes)

            ['episode_id' => '14',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '15',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '16',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '17',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '18',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '19',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '20',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '21',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '22',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '23',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '24',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '25',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '26',
                'presentateur_id' => '1',
            ],

            // Saison 5 (14 épisodes)

            ['episode_id' => '27',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '28',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '29',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '30',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '31',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '32',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '33',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '34',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '35',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '36',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '37',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '38',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '39',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '40',
                'presentateur_id' => '1',
            ],

            // Saison 6 (12 épisodes)

            ['episode_id' => '41',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '42',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '43',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '44',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '45',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '46',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '47',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '48',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '49',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '50',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '51',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '52',
                'presentateur_id' => '1',
            ],

            // Saison 7 (10 épisodes)

            ['episode_id' => '53',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '54',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '55',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '56',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '57',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '58',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '59',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '60',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '61',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '62',
                'presentateur_id' => '1',
            ],

            // Saison 8 (20 épisodes)

            ['episode_id' => '63',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '64',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '65',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '66',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '67',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '68',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '69',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '70',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '71',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '72',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '73',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '74',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '75',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '76',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '77',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '78',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '79',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '80',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '81',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '82',
                'presentateur_id' => '1',
            ],

            // Saison 9 (17 épisodes)

            ['episode_id' => '83',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '84',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '85',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '86',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '87',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '88',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '89',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '90',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '91',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '92',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '93',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '94',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '95',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '96',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '97',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '98',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '99',
                'presentateur_id' => '1',
            ],

            // Saison 10 (17 épisodes)

            ['episode_id' => '100',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '101',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '102',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '103',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '104',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '105',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '106',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '107',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '108',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '109',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '110',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '111',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '112',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '113',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '114',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '115',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '116',
                'presentateur_id' => '1',
            ],

            // Saison 11 (19 épisodes)

            ['episode_id' => '117',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '118',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '119',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '120',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '121',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '122',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '123',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '124',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '125',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '126',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '127',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '128',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '129',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '130',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '131',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '132',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '133',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '134',
                'presentateur_id' => '1',
            ],
            ['episode_id' => '135',
                'presentateur_id' => '1',
            ],

            // Saison 12 (20 épisodes)

            ['episode_id' => '136',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '137',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '138',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '139',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '140',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '141',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '142',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '143',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '144',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '145',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '146',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '147',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '148',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '149',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '150',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '151',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '152',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '153',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '154',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '155',
                'presentateur_id' => '2',
            ],

            // Saison 13 (17 épisodes)

            ['episode_id' => '156',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '157',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '158',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '159',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '160',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '161',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '162',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '163',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '164',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '165',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '166',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '167',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '168',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '169',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '170',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '171',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '172',
                'presentateur_id' => '2',
            ],

            // Saison 14 (20 épisodes)
            ['episode_id' => '173',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '174',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '175',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '176',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '177',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '178',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '179',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '180',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '181',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '182',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '183',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '184',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '185',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '186',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '187',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '188',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '189',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '190',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '191',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '192',
                'presentateur_id' => '2',
            ],

            // Saison 15 (16 épisodes)

            ['episode_id' => '193',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '194',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '195',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '196',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '197',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '198',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '199',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '200',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '201',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '202',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '203',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '204',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '205',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '206',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '207',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '208',
                'presentateur_id' => '2',
            ],

            // Saison 16 (13 épisodes)

            ['episode_id' => '209',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '210',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '211',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '212',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '213',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '214',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '215',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '216',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '217',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '218',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '219',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '220',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '221',
                'presentateur_id' => '2',
            ],

            // Saison 17 (5 épisodes)

            ['episode_id' => '222',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '223',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '224',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '225',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '226',
                'presentateur_id' => '2',
            ],

            // Saison 18 (8 épisodes)

            ['episode_id' => '227',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '228',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '229',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '230',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '231',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '232',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '233',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '234',
                'presentateur_id' => '2',
            ],

            // Saison 19 (2 épisodes)

            ['episode_id' => '235',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '236',
                'presentateur_id' => '2',
            ],

            // Saison 20 (7 épisodes)

            ['episode_id' => '237',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '238',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '239',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '240',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '241',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '242',
                'presentateur_id' => '2',
            ],
            ['episode_id' => '243',
                'presentateur_id' => '2',
            ],
            ]);
    }
}
